/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eticketapplication;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;


public class MainAppFrame extends javax.swing.JFrame {

  /**
   * Creates new form MainAppFrame
   */
  
  public MainAppFrame() {
    initComponents();
    tglBerangkatDateHome.setDateFormatString("dd-MMM-yyyy");
    ContainerPages.setSelectedIndex(0);
    setVisibleNav(false);
  }
  //hidden navBar
  public void setVisibleNav(boolean x){
      homeNavBtn.setVisible(x);
      pesanTiketNavBtn.setVisible(x);
      transaksiNavBtn.setVisible(x);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do
   * NOT modify this code. The content of this method is always regenerated by the Form
   * Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jadwal1 = new javax.swing.JPanel();
        namaKereta = new javax.swing.JLabel();
        awal = new javax.swing.JLabel();
        sampai = new javax.swing.JLabel();
        durasi = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        keberangkatan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pesanTiketNavBtn = new javax.swing.JButton();
        transaksiNavBtn = new javax.swing.JButton();
        homeNavBtn = new javax.swing.JButton();
        ContainerPages = new javax.swing.JTabbedPane();
        LoginPage = new javax.swing.JPanel();
        emailFieldLogin = new javax.swing.JTextField();
        emailLabelLogin = new javax.swing.JLabel();
        passwordLabelLogin = new javax.swing.JLabel();
        masukBtnLogin = new javax.swing.JButton();
        passwordFieldLogin = new javax.swing.JPasswordField();
        daftarBtnLogin = new javax.swing.JButton();
        SignUpPage = new javax.swing.JPanel();
        emailLabelSignup = new javax.swing.JLabel();
        emailFieldSignUp = new javax.swing.JTextField();
        passwordLabelSignup = new javax.swing.JLabel();
        passwordFieldSignup = new javax.swing.JPasswordField();
        teleponLabelSignup = new javax.swing.JLabel();
        teleponFieldSignUp = new javax.swing.JTextField();
        namaLabelSignup = new javax.swing.JLabel();
        namaFieldSignUp = new javax.swing.JTextField();
        daftarBtnSignUp = new javax.swing.JButton();
        HomePage = new javax.swing.JPanel();
        titleLabelHome = new javax.swing.JLabel();
        awalListHome = new javax.swing.JComboBox<>();
        awalLabelHome = new javax.swing.JLabel();
        tujuanLabelHome = new javax.swing.JLabel();
        tujuanListHome = new javax.swing.JComboBox<>();
        tanggalLabelHome = new javax.swing.JLabel();
        tglBerangkatDateHome = new com.toedter.calendar.JDateChooser();
        penumpangLabelHome = new javax.swing.JLabel();
        penumpangSpinnerHome = new javax.swing.JSpinner();
        cariTiketBtnHome = new javax.swing.JButton();
        JadwalPage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jadwal2 = new javax.swing.JPanel();
        namaKereta1 = new javax.swing.JLabel();
        awal1 = new javax.swing.JLabel();
        sampai1 = new javax.swing.JLabel();
        durasi1 = new javax.swing.JLabel();
        harga1 = new javax.swing.JLabel();
        keberangkatan1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jadwal3 = new javax.swing.JPanel();
        namaKereta2 = new javax.swing.JLabel();
        awal2 = new javax.swing.JLabel();
        sampai2 = new javax.swing.JLabel();
        durasi2 = new javax.swing.JLabel();
        harga2 = new javax.swing.JLabel();
        keberangkatan2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jadwal4 = new javax.swing.JPanel();
        namaKereta3 = new javax.swing.JLabel();
        awal3 = new javax.swing.JLabel();
        sampai3 = new javax.swing.JLabel();
        durasi3 = new javax.swing.JLabel();
        harga3 = new javax.swing.JLabel();
        keberangkatan3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PesanTiketPage = new javax.swing.JPanel();
        tiketPanelPesanTiket = new javax.swing.JPanel();
        tglTiketLabelPesanTiket = new javax.swing.JLabel();
        destinasiLabelPesanTiket = new javax.swing.JLabel();
        jamTiketLabelPesanTiket = new javax.swing.JLabel();
        namaKeretaLabelPesanTiket = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PilihKursiPage = new javax.swing.JPanel();
        gerbongPilihKursi = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        pilihGerbongComboPilihKursi = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        DetailPembayaranPage = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bayarBtnDetailPembayaran = new javax.swing.JButton();
        FinalPembayaran = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        PesanMakananPage = new javax.swing.JPanel();

        jadwal1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        namaKereta.setText("Nama Kereta");

        awal.setText("Awal");

        sampai.setText("Sampai");

        durasi.setText("Durasi");

        harga.setText("Harga");

        keberangkatan.setText("Keberangkatan");

        jLabel2.setText("Tujuan");

        javax.swing.GroupLayout jadwal1Layout = new javax.swing.GroupLayout(jadwal1);
        jadwal1.setLayout(jadwal1Layout);
        jadwal1Layout.setHorizontalGroup(
            jadwal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadwal1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jadwal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jadwal1Layout.createSequentialGroup()
                        .addComponent(namaKereta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(harga))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jadwal1Layout.createSequentialGroup()
                        .addGroup(jadwal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jadwal1Layout.createSequentialGroup()
                                .addComponent(awal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(durasi)
                                .addGap(162, 162, 162))
                            .addGroup(jadwal1Layout.createSequentialGroup()
                                .addComponent(keberangkatan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jadwal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(sampai))))
                .addGap(54, 54, 54))
        );
        jadwal1Layout.setVerticalGroup(
            jadwal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadwal1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jadwal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaKereta)
                    .addComponent(harga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jadwal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keberangkatan)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jadwal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sampai)
                    .addComponent(durasi)
                    .addComponent(awal)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 1280, 720));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pesanTiketNavBtn.setText("Pesan Tiket");
        pesanTiketNavBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanTiketNavBtnActionPerformed(evt);
            }
        });
        getContentPane().add(pesanTiketNavBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        transaksiNavBtn.setText("Transaksi");
        transaksiNavBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiNavBtnActionPerformed(evt);
            }
        });
        getContentPane().add(transaksiNavBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        homeNavBtn.setText("Home");
        homeNavBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeNavBtnActionPerformed(evt);
            }
        });
        getContentPane().add(homeNavBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        emailLabelLogin.setText("Email");

        passwordLabelLogin.setText("Password");

        masukBtnLogin.setText("Masuk");
        masukBtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukBtnLoginActionPerformed(evt);
            }
        });

        daftarBtnLogin.setText("Daftar");
        daftarBtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarBtnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPageLayout = new javax.swing.GroupLayout(LoginPage);
        LoginPage.setLayout(LoginPageLayout);
        LoginPageLayout.setHorizontalGroup(
            LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPageLayout.createSequentialGroup()
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPageLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLabelLogin)
                            .addComponent(passwordLabelLogin))
                        .addGap(29, 29, 29)
                        .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailFieldLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(passwordFieldLogin))
                        .addGap(30, 30, 30)
                        .addComponent(masukBtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPageLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(daftarBtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        LoginPageLayout.setVerticalGroup(
            LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPageLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabelLogin))
                .addGap(18, 18, 18)
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabelLogin)
                    .addComponent(passwordFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(daftarBtnLogin)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(masukBtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        ContainerPages.addTab("Login", LoginPage);

        emailLabelSignup.setText("Email");

        passwordLabelSignup.setText("Password");

        passwordFieldSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldSignupActionPerformed(evt);
            }
        });

        teleponLabelSignup.setText("Telepon");

        namaLabelSignup.setText("Nama");

        daftarBtnSignUp.setText("Daftar");
        daftarBtnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarBtnSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SignUpPageLayout = new javax.swing.GroupLayout(SignUpPage);
        SignUpPage.setLayout(SignUpPageLayout);
        SignUpPageLayout.setHorizontalGroup(
            SignUpPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPageLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(SignUpPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SignUpPageLayout.createSequentialGroup()
                        .addComponent(namaLabelSignup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(namaFieldSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SignUpPageLayout.createSequentialGroup()
                        .addGroup(SignUpPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLabelSignup)
                            .addComponent(passwordLabelSignup)
                            .addComponent(teleponLabelSignup))
                        .addGap(29, 29, 29)
                        .addGroup(SignUpPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(teleponFieldSignUp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailFieldSignUp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordFieldSignup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))))
                .addGap(43, 43, 43)
                .addComponent(daftarBtnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        SignUpPageLayout.setVerticalGroup(
            SignUpPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignUpPageLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(SignUpPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabelSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaFieldSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(SignUpPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignUpPageLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(SignUpPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SignUpPageLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(teleponLabelSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(teleponFieldSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(SignUpPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SignUpPageLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(emailLabelSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(emailFieldSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SignUpPageLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(daftarBtnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(SignUpPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabelSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordFieldSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        ContainerPages.addTab("SignUp", SignUpPage);

        titleLabelHome.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 18)); // NOI18N
        titleLabelHome.setText("Selamat Datang di Aplikasi BLI-Tiket");

        awalListHome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Surabaya", "Sidoarjo", "Mojokerto", "Malang" }));
        awalListHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awalListHomeActionPerformed(evt);
            }
        });

        awalLabelHome.setText("Awal");

        tujuanLabelHome.setText("Tujuan");

        tujuanListHome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Surabaya", "Sidoarjo", "Mojokerto", "Malang" }));
        tujuanListHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuanListHomeActionPerformed(evt);
            }
        });

        tanggalLabelHome.setText("Tanggal Berangkat");

        penumpangLabelHome.setText("Jumlah Penumpang");

        penumpangSpinnerHome.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        penumpangSpinnerHome.setRequestFocusEnabled(false);

        cariTiketBtnHome.setBackground(new java.awt.Color(153, 204, 255));
        cariTiketBtnHome.setText("Cari Tiket");

        javax.swing.GroupLayout HomePageLayout = new javax.swing.GroupLayout(HomePage);
        HomePage.setLayout(HomePageLayout);
        HomePageLayout.setHorizontalGroup(
            HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HomePageLayout.createSequentialGroup()
                        .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(awalListHome, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(awalLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tujuanListHome, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tujuanLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(HomePageLayout.createSequentialGroup()
                        .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tanggalLabelHome, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(tglBerangkatDateHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomePageLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(penumpangSpinnerHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePageLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(penumpangLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(cariTiketBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        HomePageLayout.setVerticalGroup(
            HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(titleLabelHome)
                .addGap(18, 18, 18)
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HomePageLayout.createSequentialGroup()
                        .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(awalLabelHome)
                            .addComponent(tujuanLabelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(awalListHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tujuanListHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggalLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(penumpangLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglBerangkatDateHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(penumpangSpinnerHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(cariTiketBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        ContainerPages.addTab("Home", HomePage);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jadwal2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jadwal2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jadwal2MouseClicked(evt);
            }
        });

        namaKereta1.setText("Nama Kereta");

        awal1.setText("Awal");

        sampai1.setText("Sampai");

        durasi1.setText("Durasi");

        harga1.setText("Harga");

        keberangkatan1.setText("Keberangkatan");

        jLabel3.setText("Tujuan");

        javax.swing.GroupLayout jadwal2Layout = new javax.swing.GroupLayout(jadwal2);
        jadwal2.setLayout(jadwal2Layout);
        jadwal2Layout.setHorizontalGroup(
            jadwal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadwal2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jadwal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jadwal2Layout.createSequentialGroup()
                        .addComponent(namaKereta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(harga1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jadwal2Layout.createSequentialGroup()
                        .addGroup(jadwal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jadwal2Layout.createSequentialGroup()
                                .addComponent(awal1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jadwal2Layout.createSequentialGroup()
                                .addComponent(keberangkatan1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(198, 198, 198)
                        .addGroup(jadwal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jadwal2Layout.createSequentialGroup()
                                .addComponent(durasi1)
                                .addGap(199, 199, 199)
                                .addComponent(sampai1)))))
                .addGap(54, 54, 54))
        );
        jadwal2Layout.setVerticalGroup(
            jadwal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadwal2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jadwal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaKereta1)
                    .addComponent(harga1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jadwal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keberangkatan1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jadwal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sampai1)
                    .addComponent(durasi1)
                    .addComponent(awal1)))
        );

        jadwal3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        namaKereta2.setText("Nama Kereta");

        awal2.setText("Awal");

        sampai2.setText("Sampai");

        durasi2.setText("Durasi");

        harga2.setText("Harga");

        keberangkatan2.setText("Keberangkatan");

        jLabel4.setText("Tujuan");

        javax.swing.GroupLayout jadwal3Layout = new javax.swing.GroupLayout(jadwal3);
        jadwal3.setLayout(jadwal3Layout);
        jadwal3Layout.setHorizontalGroup(
            jadwal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadwal3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jadwal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jadwal3Layout.createSequentialGroup()
                        .addComponent(namaKereta2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(harga2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jadwal3Layout.createSequentialGroup()
                        .addComponent(awal2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                        .addComponent(durasi2)
                        .addGap(205, 205, 205)
                        .addComponent(sampai2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jadwal3Layout.createSequentialGroup()
                        .addComponent(keberangkatan2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addGap(54, 54, 54))
        );
        jadwal3Layout.setVerticalGroup(
            jadwal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadwal3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jadwal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaKereta2)
                    .addComponent(harga2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jadwal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keberangkatan2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jadwal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sampai2)
                    .addComponent(durasi2)
                    .addComponent(awal2)))
        );

        jadwal4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        namaKereta3.setText("Nama Kereta");

        awal3.setText("Awal");

        sampai3.setText("Sampai");

        durasi3.setText("Durasi");

        harga3.setText("Harga");

        keberangkatan3.setText("Keberangkatan");

        jLabel5.setText("Tujuan");

        javax.swing.GroupLayout jadwal4Layout = new javax.swing.GroupLayout(jadwal4);
        jadwal4.setLayout(jadwal4Layout);
        jadwal4Layout.setHorizontalGroup(
            jadwal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadwal4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jadwal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jadwal4Layout.createSequentialGroup()
                        .addComponent(namaKereta3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(harga3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jadwal4Layout.createSequentialGroup()
                        .addComponent(awal3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                        .addComponent(durasi3)
                        .addGap(205, 205, 205)
                        .addComponent(sampai3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jadwal4Layout.createSequentialGroup()
                        .addComponent(keberangkatan3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGap(54, 54, 54))
        );
        jadwal4Layout.setVerticalGroup(
            jadwal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadwal4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jadwal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaKereta3)
                    .addComponent(harga3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jadwal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keberangkatan3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jadwal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sampai3)
                    .addComponent(durasi3)
                    .addComponent(awal3)))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jadwal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jadwal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jadwal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jadwal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jadwal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jadwal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jScrollPane1.setViewportView(jPanel7);

        javax.swing.GroupLayout JadwalPageLayout = new javax.swing.GroupLayout(JadwalPage);
        JadwalPage.setLayout(JadwalPageLayout);
        JadwalPageLayout.setHorizontalGroup(
            JadwalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        JadwalPageLayout.setVerticalGroup(
            JadwalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );

        ContainerPages.addTab("Jadwal", JadwalPage);

        tiketPanelPesanTiket.setBackground(new java.awt.Color(255, 255, 255));
        tiketPanelPesanTiket.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tglTiketLabelPesanTiket.setText("tanggal_tiket");

        destinasiLabelPesanTiket.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        destinasiLabelPesanTiket.setForeground(new java.awt.Color(51, 51, 255));
        destinasiLabelPesanTiket.setText("Destinasi Awal - Destinasi Tujuan");

        jamTiketLabelPesanTiket.setText("jam_tiket");

        namaKeretaLabelPesanTiket.setText("nama_kereta");

        javax.swing.GroupLayout tiketPanelPesanTiketLayout = new javax.swing.GroupLayout(tiketPanelPesanTiket);
        tiketPanelPesanTiket.setLayout(tiketPanelPesanTiketLayout);
        tiketPanelPesanTiketLayout.setHorizontalGroup(
            tiketPanelPesanTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tiketPanelPesanTiketLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(tiketPanelPesanTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaKeretaLabelPesanTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamTiketLabelPesanTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglTiketLabelPesanTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinasiLabelPesanTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        tiketPanelPesanTiketLayout.setVerticalGroup(
            tiketPanelPesanTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tiketPanelPesanTiketLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(tglTiketLabelPesanTiket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(destinasiLabelPesanTiket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jamTiketLabelPesanTiket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namaKeretaLabelPesanTiket)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jButton1.setText("Lanjutkan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PesanTiketPageLayout = new javax.swing.GroupLayout(PesanTiketPage);
        PesanTiketPage.setLayout(PesanTiketPageLayout);
        PesanTiketPageLayout.setHorizontalGroup(
            PesanTiketPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesanTiketPageLayout.createSequentialGroup()
                .addGroup(PesanTiketPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PesanTiketPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tiketPanelPesanTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PesanTiketPageLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jButton1)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        PesanTiketPageLayout.setVerticalGroup(
            PesanTiketPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesanTiketPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tiketPanelPesanTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(54, 54, 54))
        );

        ContainerPages.addTab("PesanTiket", PesanTiketPage);

        gerbongPilihKursi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRadioButton1.setText("1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Gerbong 1");

        jRadioButton2.setText("1");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("1");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton7.setText("1");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jRadioButton8.setText("1");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jRadioButton9.setText("1");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        jRadioButton10.setText("1");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        jRadioButton11.setText("1");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        jRadioButton12.setText("1");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        jRadioButton13.setText("1");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        jRadioButton14.setText("1");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });

        jRadioButton15.setText("1");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });

        jRadioButton16.setText("1");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });

        jRadioButton17.setText("1");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });

        jRadioButton18.setText("1");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });

        jRadioButton19.setText("1");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });

        jRadioButton20.setText("1");
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });

        jRadioButton21.setText("1");
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21ActionPerformed(evt);
            }
        });

        jRadioButton22.setText("1");
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton22ActionPerformed(evt);
            }
        });

        jRadioButton23.setText("1");
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23ActionPerformed(evt);
            }
        });

        jRadioButton24.setText("1");
        jRadioButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton24ActionPerformed(evt);
            }
        });

        jRadioButton25.setText("1");
        jRadioButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton25ActionPerformed(evt);
            }
        });

        jRadioButton26.setText("1");
        jRadioButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton26ActionPerformed(evt);
            }
        });

        jRadioButton27.setText("1");
        jRadioButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton27ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gerbongPilihKursiLayout = new javax.swing.GroupLayout(gerbongPilihKursi);
        gerbongPilihKursi.setLayout(gerbongPilihKursiLayout);
        gerbongPilihKursiLayout.setHorizontalGroup(
            gerbongPilihKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gerbongPilihKursiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(140, 140, 140))
            .addGroup(gerbongPilihKursiLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(gerbongPilihKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gerbongPilihKursiLayout.createSequentialGroup()
                        .addComponent(jRadioButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton11))
                    .addGroup(gerbongPilihKursiLayout.createSequentialGroup()
                        .addComponent(jRadioButton9)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton10))
                    .addGroup(gerbongPilihKursiLayout.createSequentialGroup()
                        .addComponent(jRadioButton12)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton15))
                    .addGroup(gerbongPilihKursiLayout.createSequentialGroup()
                        .addComponent(jRadioButton13)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton14))
                    .addGroup(gerbongPilihKursiLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton7))
                    .addGroup(gerbongPilihKursiLayout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(gerbongPilihKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gerbongPilihKursiLayout.createSequentialGroup()
                        .addComponent(jRadioButton20)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton23))
                    .addGroup(gerbongPilihKursiLayout.createSequentialGroup()
                        .addComponent(jRadioButton21)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton22))
                    .addGroup(gerbongPilihKursiLayout.createSequentialGroup()
                        .addComponent(jRadioButton24)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton27))
                    .addGroup(gerbongPilihKursiLayout.createSequentialGroup()
                        .addComponent(jRadioButton25)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton26))
                    .addGroup(gerbongPilihKursiLayout.createSequentialGroup()
                        .addComponent(jRadioButton16)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton19))
                    .addGroup(gerbongPilihKursiLayout.createSequentialGroup()
                        .addComponent(jRadioButton17)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton18)))
                .addGap(57, 57, 57))
        );
        gerbongPilihKursiLayout.setVerticalGroup(
            gerbongPilihKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gerbongPilihKursiLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gerbongPilihKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gerbongPilihKursiLayout.createSequentialGroup()
                        .addGroup(gerbongPilihKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gerbongPilihKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3))
                        .addGap(18, 18, 18)
                        .addGroup(gerbongPilihKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gerbongPilihKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton9)
                            .addComponent(jRadioButton10))
                        .addGap(18, 18, 18)
                        .addGroup(gerbongPilihKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton12)
                            .addComponent(jRadioButton15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gerbongPilihKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton13)
                            .addComponent(jRadioButton14)))
                    .addGroup(gerbongPilihKursiLayout.createSequentialGroup()
                        .addGroup(gerbongPilihKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton16)
                            .addComponent(jRadioButton19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gerbongPilihKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton17)
                            .addComponent(jRadioButton18))
                        .addGap(18, 18, 18)
                        .addGroup(gerbongPilihKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton20)
                            .addComponent(jRadioButton23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gerbongPilihKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton21)
                            .addComponent(jRadioButton22))
                        .addGap(18, 18, 18)
                        .addGroup(gerbongPilihKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton24)
                            .addComponent(jRadioButton27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gerbongPilihKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton25)
                            .addComponent(jRadioButton26))))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pilihGerbongComboPilihKursi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerbong 1", "Gerbong 2", "Gerbong 3", "Gerbong 4" }));
        pilihGerbongComboPilihKursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihGerbongComboPilihKursiActionPerformed(evt);
            }
        });

        jButton2.setText("Pesan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PilihKursiPageLayout = new javax.swing.GroupLayout(PilihKursiPage);
        PilihKursiPage.setLayout(PilihKursiPageLayout);
        PilihKursiPageLayout.setHorizontalGroup(
            PilihKursiPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PilihKursiPageLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(PilihKursiPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pilihGerbongComboPilihKursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(gerbongPilihKursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PilihKursiPageLayout.setVerticalGroup(
            PilihKursiPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PilihKursiPageLayout.createSequentialGroup()
                .addComponent(gerbongPilihKursi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PilihKursiPageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pilihGerbongComboPilihKursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton2)
                .addGap(78, 78, 78))
        );

        ContainerPages.addTab("PilihKursi", PilihKursiPage);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Awal");

        jLabel9.setText("Tujuan");

        jLabel10.setText("Tanggal");

        jLabel11.setText("Nama Kereta");

        jLabel12.setText("Gerbong");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BliPay", "Transfer Bank", "Alfamart", "Indomaret" }));

        jLabel1.setText("Total Harga");

        jLabel7.setText("Metode Pembayaran");

        jLabel13.setText("Detail Pembayaran");

        jLabel14.setText("Harga Tiket");

        jLabel15.setText("Penumpang");

        jLabel16.setText("2");

        bayarBtnDetailPembayaran.setText("Bayar");
        bayarBtnDetailPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarBtnDetailPembayaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DetailPembayaranPageLayout = new javax.swing.GroupLayout(DetailPembayaranPage);
        DetailPembayaranPage.setLayout(DetailPembayaranPageLayout);
        DetailPembayaranPageLayout.setHorizontalGroup(
            DetailPembayaranPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailPembayaranPageLayout.createSequentialGroup()
                .addGroup(DetailPembayaranPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bayarBtnDetailPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DetailPembayaranPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(DetailPembayaranPageLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15)
                            .addGap(80, 80, 80)
                            .addComponent(jLabel16))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DetailPembayaranPageLayout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addGroup(DetailPembayaranPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(DetailPembayaranPageLayout.createSequentialGroup()
                                    .addGroup(DetailPembayaranPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(DetailPembayaranPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14)))))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        DetailPembayaranPageLayout.setVerticalGroup(
            DetailPembayaranPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailPembayaranPageLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DetailPembayaranPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DetailPembayaranPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DetailPembayaranPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(bayarBtnDetailPembayaran)
                .addGap(14, 14, 14))
        );

        ContainerPages.addTab("DetailPembayaran", DetailPembayaranPage);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel17.setText("Pembayaran Sukses!");

        javax.swing.GroupLayout FinalPembayaranLayout = new javax.swing.GroupLayout(FinalPembayaran);
        FinalPembayaran.setLayout(FinalPembayaranLayout);
        FinalPembayaranLayout.setHorizontalGroup(
            FinalPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FinalPembayaranLayout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );
        FinalPembayaranLayout.setVerticalGroup(
            FinalPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinalPembayaranLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel17)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        ContainerPages.addTab("FinalPm", FinalPembayaran);

        javax.swing.GroupLayout PesanMakananPageLayout = new javax.swing.GroupLayout(PesanMakananPage);
        PesanMakananPage.setLayout(PesanMakananPageLayout);
        PesanMakananPageLayout.setHorizontalGroup(
            PesanMakananPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        PesanMakananPageLayout.setVerticalGroup(
            PesanMakananPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        ContainerPages.addTab("PesanMakanan", PesanMakananPage);

        getContentPane().add(ContainerPages, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void homeNavBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeNavBtnActionPerformed
    ContainerPages.setSelectedIndex(2);
    
  }//GEN-LAST:event_homeNavBtnActionPerformed

    private void pesanTiketNavBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanTiketNavBtnActionPerformed
     ContainerPages.setSelectedIndex(4);
    }//GEN-LAST:event_pesanTiketNavBtnActionPerformed

    private void awalListHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awalListHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_awalListHomeActionPerformed

    private void tujuanListHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuanListHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tujuanListHomeActionPerformed

    private void passwordFieldSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldSignupActionPerformed

    private void transaksiNavBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiNavBtnActionPerformed
//        MainAppFrame mainFrame = new MainAppFrame();
//        jDateChooser1.setDateFormatString("dd-Month-yyyy");
        Date date = tglBerangkatDateHome.getDate();
        System.out.println(date);
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");  
        System.out.println(df.format(date));
//        mainFrame.titleLabelHome.setText(df.format(date));// TODO add your handling code here:
    }//GEN-LAST:event_transaksiNavBtnActionPerformed

    private void masukBtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukBtnLoginActionPerformed
        // TODO add your handling code here:
        ContainerPages.setSelectedIndex(2);
        setVisibleNav(true);
    }//GEN-LAST:event_masukBtnLoginActionPerformed

    private void daftarBtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarBtnLoginActionPerformed
        // TODO add your handling code here:
        ContainerPages.setSelectedIndex(1);
        setVisibleNav(false);
    }//GEN-LAST:event_daftarBtnLoginActionPerformed

    private void daftarBtnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarBtnSignUpActionPerformed
        // TODO add your handling code here:
        ContainerPages.setSelectedIndex(0);
    }//GEN-LAST:event_daftarBtnSignUpActionPerformed

    private void pilihGerbongComboPilihKursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihGerbongComboPilihKursiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihGerbongComboPilihKursiActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton19ActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton21ActionPerformed

    private void jRadioButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton22ActionPerformed

    private void jRadioButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton23ActionPerformed

    private void jRadioButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton24ActionPerformed

    private void jRadioButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton25ActionPerformed

    private void jRadioButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton26ActionPerformed

    private void jRadioButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton27ActionPerformed

    private void jadwal2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jadwal2MouseClicked
        // TODO add your handling code here:
        ContainerPages.setSelectedIndex(4);
    }//GEN-LAST:event_jadwal2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ContainerPages.setSelectedIndex(5);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ContainerPages.setSelectedIndex(6);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void bayarBtnDetailPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarBtnDetailPembayaranActionPerformed
        // TODO add your handling code here:
        ContainerPages.setSelectedIndex(7);
        
    }//GEN-LAST:event_bayarBtnDetailPembayaranActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainAppFrame().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ContainerPages;
    private javax.swing.JPanel DetailPembayaranPage;
    private javax.swing.JPanel FinalPembayaran;
    private javax.swing.JPanel HomePage;
    private javax.swing.JPanel JadwalPage;
    private javax.swing.JPanel LoginPage;
    private javax.swing.JPanel PesanMakananPage;
    private javax.swing.JPanel PesanTiketPage;
    private javax.swing.JPanel PilihKursiPage;
    private javax.swing.JPanel SignUpPage;
    private javax.swing.JLabel awal;
    private javax.swing.JLabel awal1;
    private javax.swing.JLabel awal2;
    private javax.swing.JLabel awal3;
    private javax.swing.JLabel awalLabelHome;
    private javax.swing.JComboBox<String> awalListHome;
    private javax.swing.JButton bayarBtnDetailPembayaran;
    private javax.swing.JButton cariTiketBtnHome;
    private javax.swing.JButton daftarBtnLogin;
    private javax.swing.JButton daftarBtnSignUp;
    private javax.swing.JLabel destinasiLabelPesanTiket;
    private javax.swing.JLabel durasi;
    private javax.swing.JLabel durasi1;
    private javax.swing.JLabel durasi2;
    private javax.swing.JLabel durasi3;
    private javax.swing.JTextField emailFieldLogin;
    private javax.swing.JTextField emailFieldSignUp;
    private javax.swing.JLabel emailLabelLogin;
    private javax.swing.JLabel emailLabelSignup;
    private javax.swing.JPanel gerbongPilihKursi;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel harga1;
    private javax.swing.JLabel harga2;
    private javax.swing.JLabel harga3;
    private javax.swing.JButton homeNavBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jadwal1;
    private javax.swing.JPanel jadwal2;
    private javax.swing.JPanel jadwal3;
    private javax.swing.JPanel jadwal4;
    private javax.swing.JLabel jamTiketLabelPesanTiket;
    private javax.swing.JLabel keberangkatan;
    private javax.swing.JLabel keberangkatan1;
    private javax.swing.JLabel keberangkatan2;
    private javax.swing.JLabel keberangkatan3;
    private javax.swing.JButton masukBtnLogin;
    private javax.swing.JTextField namaFieldSignUp;
    private javax.swing.JLabel namaKereta;
    private javax.swing.JLabel namaKereta1;
    private javax.swing.JLabel namaKereta2;
    private javax.swing.JLabel namaKereta3;
    private javax.swing.JLabel namaKeretaLabelPesanTiket;
    private javax.swing.JLabel namaLabelSignup;
    private javax.swing.JPasswordField passwordFieldLogin;
    private javax.swing.JPasswordField passwordFieldSignup;
    private javax.swing.JLabel passwordLabelLogin;
    private javax.swing.JLabel passwordLabelSignup;
    private javax.swing.JLabel penumpangLabelHome;
    private javax.swing.JSpinner penumpangSpinnerHome;
    private javax.swing.JButton pesanTiketNavBtn;
    private javax.swing.JComboBox<String> pilihGerbongComboPilihKursi;
    private javax.swing.JLabel sampai;
    private javax.swing.JLabel sampai1;
    private javax.swing.JLabel sampai2;
    private javax.swing.JLabel sampai3;
    private javax.swing.JLabel tanggalLabelHome;
    private javax.swing.JTextField teleponFieldSignUp;
    private javax.swing.JLabel teleponLabelSignup;
    private com.toedter.calendar.JDateChooser tglBerangkatDateHome;
    private javax.swing.JLabel tglTiketLabelPesanTiket;
    private javax.swing.JPanel tiketPanelPesanTiket;
    private javax.swing.JLabel titleLabelHome;
    private javax.swing.JButton transaksiNavBtn;
    private javax.swing.JLabel tujuanLabelHome;
    private javax.swing.JComboBox<String> tujuanListHome;
    // End of variables declaration//GEN-END:variables
}
